import React from 'react';
import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { TrendingUp, Leaf, Zap, Car, Utensils, Trash2, ShoppingBag, Download } from 'lucide-react';
import jsPDF from 'jspdf';

const Dashboard = ({ data }) => {
  const { baseline, refined } = data;

  // Prepare data for pie chart
  const pieData = Object.entries(baseline.breakdown).map(([category, value]) => ({
    name: category.charAt(0).toUpperCase() + category.slice(1),
    value: Math.abs(value),
    color: getCategoryColor(category)
  }));

  // Prepare data for comparison chart
  const comparisonData = Object.entries(baseline.breakdown).map(([category, value]) => ({
    category: category.charAt(0).toUpperCase() + category.slice(1),
    baseline: Math.abs(value),
    refined: refined ? Math.abs(refined.breakdown[category] || 0) : 0
  }));

  const categoryIcons = {
    transport: Car,
    food: Utensils,
    energy: Zap,
    waste: Trash2,
    consumption: ShoppingBag
  };

  const categoryColors = {
    transport: '#3B82F6',
    food: '#EF4444',
    energy: '#F59E0B',
    waste: '#8B5CF6',
    consumption: '#10B981'
  };

  function getCategoryColor(category) {
    return categoryColors[category] || '#6B7280';
  }

  const totalBaseline = baseline.baseline_total;
  const totalRefined = refined ? refined.refined_total : null;
  const improvement = totalRefined ? ((totalBaseline - totalRefined) / totalBaseline * 100) : 0;

  const exportToPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    
    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Carbon Footprint Report', pageWidth / 2, 30, { align: 'center' });
    
    // Date
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, 40, { align: 'center' });
    
    // Summary
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 20, 60);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Baseline Footprint: ${totalBaseline.toFixed(1)} kg CO₂`, 20, 75);
    
    if (totalRefined) {
      doc.text(`AI Refined Footprint: ${totalRefined.toFixed(1)} kg CO₂`, 20, 85);
      doc.text(`Improvement: ${improvement.toFixed(1)}% reduction`, 20, 95);
    }
    
    // Breakdown
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Emissions Breakdown', 20, 115);
    
    let yPos = 130;
    Object.entries(baseline.breakdown).forEach(([category, value]) => {
      const percentage = (Math.abs(value) / totalBaseline) * 100;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.text(`${category.charAt(0).toUpperCase() + category.slice(1)}: ${Math.abs(value).toFixed(1)} kg CO₂ (${percentage.toFixed(1)}%)`, 20, yPos);
      yPos += 10;
    });
    
    // Recommendations
    if (yPos > 250) {
      doc.addPage();
      yPos = 30;
    }
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations', 20, yPos);
    
    yPos += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    Object.entries(baseline.breakdown).forEach(([category, value]) => {
      const percentage = (Math.abs(value) / totalBaseline) * 100;
      if (percentage > 20) {
        doc.text(`• Consider reducing ${category} consumption (${percentage.toFixed(1)}% of footprint)`, 20, yPos);
        yPos += 10;
      }
    });
    
    if (totalRefined && improvement > 0) {
      doc.text(`• AI refinement improved accuracy by ${improvement.toFixed(1)}%`, 20, yPos);
    }
    
    // Footer
    const footerY = pageHeight - 20;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Generated by EcoTrack - Hybrid Carbon Footprint Tracker', pageWidth / 2, footerY, { align: 'center' });
    
    // Save the PDF
    doc.save('carbon-footprint-report.pdf');
  };

  return (
    <div className="space-y-6">
      {/* Export Button */}
      <div className="flex justify-end">
        <button
          onClick={exportToPDF}
          className="btn-secondary flex items-center"
        >
          <Download className="w-4 h-4 mr-2" />
          Export PDF Report
        </button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="card text-center">
          <div className="flex items-center justify-center mb-2">
            <Leaf className="w-6 h-6 text-eco-dark mr-2" />
            <h3 className="text-lg font-semibold text-gray-900">Baseline Footprint</h3>
          </div>
          <div className="text-3xl font-bold text-gray-900 mb-1">
            {totalBaseline.toFixed(1)}
          </div>
          <div className="text-sm text-gray-600">kg CO₂</div>
        </div>

        {totalRefined && (
          <div className="card text-center">
            <div className="flex items-center justify-center mb-2">
              <TrendingUp className="w-6 h-6 text-blue-600 mr-2" />
              <h3 className="text-lg font-semibold text-gray-900">AI Refined</h3>
            </div>
            <div className="text-3xl font-bold text-blue-600 mb-1">
              {totalRefined.toFixed(1)}
            </div>
            <div className="text-sm text-gray-600">kg CO₂</div>
          </div>
        )}

        {totalRefined && (
          <div className="card text-center">
            <div className="flex items-center justify-center mb-2">
              <TrendingUp className="w-6 h-6 text-green-600 mr-2" />
              <h3 className="text-lg font-semibold text-gray-900">Improvement</h3>
            </div>
            <div className="text-3xl font-bold text-green-600 mb-1">
              {improvement.toFixed(1)}%
            </div>
            <div className="text-sm text-gray-600">reduction</div>
          </div>
        )}
      </div>

      {/* Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Pie Chart */}
        <div className="card">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Emissions Breakdown</h3>
          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                data={pieData}
                cx="50%"
                cy="50%"
                labelLine={false}
                label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                outerRadius={80}
                fill="#8884d8"
                dataKey="value"
              >
                {pieData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Pie>
              <Tooltip formatter={(value) => [`${value.toFixed(1)} kg CO₂`, 'Emissions']} />
            </PieChart>
          </ResponsiveContainer>
        </div>

        {/* Comparison Chart */}
        {totalRefined && (
          <div className="card">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Baseline vs AI Refined</h3>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={comparisonData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="category" />
                <YAxis />
                <Tooltip formatter={(value) => [`${value.toFixed(1)} kg CO₂`, 'Emissions']} />
                <Legend />
                <Bar dataKey="baseline" fill="#6B7280" name="Baseline" />
                <Bar dataKey="refined" fill="#3B82F6" name="AI Refined" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        )}
      </div>

      {/* Detailed Breakdown */}
      <div className="card">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Detailed Breakdown</h3>
        <div className="space-y-4">
          {Object.entries(baseline.breakdown).map(([category, value]) => {
            const Icon = categoryIcons[category];
            const color = categoryColors[category];
            const refinedValue = refined ? refined.breakdown[category] : null;
            
            return (
              <div key={category} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                <div className="flex items-center">
                  <div className="p-2 rounded-full mr-3" style={{ backgroundColor: `${color}20` }}>
                    <Icon className="w-5 h-5" style={{ color }} />
                  </div>
                  <div>
                    <h4 className="font-medium text-gray-900 capitalize">{category}</h4>
                    <p className="text-sm text-gray-600">
                      {baseline.details[category] && Object.keys(baseline.details[category]).length > 0
                        ? Object.entries(baseline.details[category])
                            .map(([key, val]) => `${key}: ${val.toFixed(1)} kg CO₂`)
                            .join(', ')
                        : 'No details available'
                      }
                    </p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-lg font-semibold text-gray-900">
                    {Math.abs(value).toFixed(1)} kg CO₂
                  </div>
                  {refinedValue && (
                    <div className="text-sm text-blue-600">
                      Refined: {Math.abs(refinedValue).toFixed(1)} kg CO₂
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Insights */}
      <div className="card">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Insights & Recommendations</h3>
        <div className="space-y-3">
          {Object.entries(baseline.breakdown).map(([category, value]) => {
            const percentage = (Math.abs(value) / totalBaseline) * 100;
            if (percentage > 20) {
              return (
                <div key={category} className="p-3 bg-yellow-50 border border-yellow-200 rounded-lg">
                  <p className="text-sm text-yellow-800">
                    <strong>{category.charAt(0).toUpperCase() + category.slice(1)}</strong> accounts for {percentage.toFixed(1)}% of your footprint. 
                    Consider reducing this category for maximum impact.
                  </p>
                </div>
              );
            }
            return null;
          })}
          
          {totalRefined && improvement > 0 && (
            <div className="p-3 bg-green-50 border border-green-200 rounded-lg">
              <p className="text-sm text-green-800">
                <strong>Great news!</strong> Our AI model refined your footprint by {improvement.toFixed(1)}%, 
                providing a more accurate assessment based on your specific circumstances.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
